var battles = [
	{
		event_name: "Battles of Lexington & Concord",
		date_start: moment([1775, 3, 19]),
		date_end: null,
		location: "Lexington, Massachusetts",
		description: "The Patriots (American Revolutionaries) had been stockpiling supplies in preparation for a conflict with the British. They were also training people to fight. The British were on their way to Lexington to capture Patriot leaders. The Patriots found out ahead of the battle and were able to prepare.",
		winner: "Americans",
		loser: "British",
		people: "Paul Revere, Samuel Adams, John Hancock",
		killed_american: "49",
		wounded_american: "39",
		captured_american: "5",
		killed_british: "73",
		wounded_british: "174",
		captured_british: "53",
		consequences: "The American Revolutionary War begins!",
		left_coord: 0.7353515625,
		top_coord: 0.2979426891,
		img_url: "lexingtonConcord.png"
	},
	{
		event_name: "Capture of Fort Ticonderoga",
		date_start: moment([1775, 4, 10]),
		date_end: null,
		location: "Ticonderoga, New York",
		description: "Ethan Allen and Colonel Benedict Arnold led the capture of this fort. This fort was critical during the French and Indian War, but since that war it had fell into disrepair. Colonists were concerned because there was an ample supply of cannons, mortars, and other munitions being stored there. The Green Mountain Men, led by Allen & Benedict were able to overpower the small amount of British men guarding the Fort by attacking by surprise in the middle of the night. ",
		winner: "Americans",
		loser: "British",
		people: "Ethan Allen, Benedict Arnold",
		killed_american: "0",
		wounded_american: "1",
		captured_american: "1",
		killed_british: "0",
		wounded_british: "0",
		captured_british: "All British were captured",
		consequences: "The capture of Fort Ticonderoga was important in at least two regards. First, the supplied stored there were then transported to Boston to help the Patriot's cause. Second, the location of the Fort was advantageous because it interrupted communication for the British. The Fort connected  between Quebec and Boston and New York.",
		left_coord: 0.65673828125,
		top_coord: 0.2696546656869949,
		img_url: "ticonderoga.jpeg"
	},
	{
		event_name: "Battle of Bunker Hill",
		date_start: moment([1775, 5, 16]),
		date_end: null,
		location: "Charlestown, Massachusetts",
		description: "The Battle of Bunker Hill is part of the Seige of Boston, a series of battles in Boston Seige which took place between April 19th, 1775 and March 17th, 1776. Most of this battle took place on Breed's Hill, though it is called the Battle of Bunker Hill. This battle follows the Battles of Lexington & Concord which the Americans won. The British wanted to keep Boston harbor open and in British control. The British planned to do this by securing the land around the harbor in the Charleston hills. The Americans seeking to cut off British delivery of troops and supplies wanted to gain control of this area.",
		winner: "British",
		loser: "Americans",
		people: "Colonel William Prescott, General Thomas Gage",
		killed_american: "115",
		wounded_american: "305",
		captured_american: "30",
		killed_british: "226",
		wounded_british: "828",
		captured_british: "0",
		consequences: "Though this was a British victory, they sustained heavier losses than the Americans. Because of that, the British became more cautious and adopted different strateiges in fighting with the colonists moving forward. IT appeared that though the colonists lacked formal training as soldiers, they were still a force to be reckoned with.",
		left_coord: 0.74169921875,
		top_coord: 0.2997795738427627,
		img_url: "bunkerHill.jpg"
	},
	{
		event_name: "Battle of Cowpens",
		date_start: moment([1781, 0, 17]),
		date_end: null,
		location: "Cesnee, South Carolina",
		description: "At this point in the war, General Cornwallis leading British forces had secured South Carolina. General Daniel Morgan led the colonists again Colonel Banastre Tarleton's British forces. Morgan knew that Tarleton was leading men to fight Morgan's men. Tarleton moved his men quickly to Cowpens, South Carolina and engaged in battle quickly after their arrival, not giving time for the men to rest or build a strategy. Colonist forces executed a double envelopment where they split in two, and attacked Tarleton's men from either side. This resulted in an American victory.",
		winner: "Americans",
		loser: "British",
		people: "General Daniel Morgan, General Banastre Tarleton, General Cornwallis",
		killed_american: "25",
		wounded_american: "124",
		captured_american: "0",
		killed_british: "110",
		wounded_british: "229",
		captured_british: "829",
		consequences: "This battle provided a turning point and opportunity for the Americans to win back South Carolina. It is also a great example of the execution of a double envelopment. ",
		left_coord: 0.47021484375,
		top_coord: 0.5477590007347539,
		img_url: "cowpens.jpg"
	},
	{
		event_name: "Battle of Monmouth",
		date_start: moment([1778, 5, 28]),
		date_end: null,
		location: "Monmouth Court House, New Jersey",
		description: "This battle was part of the Philadelphia campaign. Prior to the battle, The British were in control of Philadelphia. It was also fought during extreme temperatures and a significant amount of lives were lost due to heat stroke and not from wounded received in battle. The Continental Army was led by George Washington and the British Army was led by Lieutenant General Sir Henry Clinton. The British were relocating from Philadelphia to New York City and had to move through New Jersey where this battle took place. Washington, sensing the vulnerabilities of Clinton's army, chose to attack while in transit. The goal of the Continental Army was to delay the British from arriving at their destination, which they did delay, however the British still made passage to New York City. ",
		winner: "Americans",
		loser: "British",
		people: "General Charles Lee, General Cornwallis, General George Washington, General Nathanael Greene, General Henry Clinton",
		killed_american: "106",
		wounded_american: "161",
		captured_american: "132",
		killed_british: "124",
		wounded_british: "170",
		captured_british: "64",
		consequences: "General Lee's poor leadership and communication at this battle resulted in him never holding another military command. ",
		left_coord: 0.6650390625,
		top_coord: 0.3681116825863336,
		img_url: "monmouth.jpg"
	},
	{
		event_name: "Battles of Saratoga",
		date_start: moment([1777, 6, 10]),
		date_end: null,
		location: "Stillwater, New York",
		description: "This battle was part of the Saratoga campaign. The Continental Army was led by Horatio Gates and General Benedict Arnold while the British forces were led by General John Burgoyne. Burgoyne had intended to separate the American forces in New England, but his plan went awry and instead he and his forces were trapped just south of Saratoga, New York. There they fought two smaller battles, just eighteen days apart to try and escape but there were unable. Ultimately, Burgoyne had to surrender in what is now Schuylerville, New York, resulting in a win for the Americans",
		winner: "Americans",
		loser: "British",
		people: "General John Burgoyne, Horatio Gates, General Benedict Arnold",
		killed_american: "90",
		wounded_american: "240",
		captured_american: "0",
		killed_british: "440",
		wounded_british: "695",
		captured_british: "6222",
		consequences: "This was another turning point in the war. General Burgoyne due to his performance in Saratoga was never again given a military command in the British forces. It also gave the French evidence of the strength of American forces. Following the surrender, the French entered into a formal Franco-American alliance giving the Continental Army much needed assistance and contributing to their ultimate victory in the war.",
		left_coord: 0.6611328125,
		top_coord: 0.2920646583394563,
		img_url: "saratoga.jpg"
	},
	{
		event_name: "Battle of Yorktown",
		date_start: moment([1781, 8, 10]),
		date_end: null,
		location: "Yorktown, Virginia",
		description: "This is the last major battle in the American Revolutionary War. Leading the Continental Army was General George Washington, and leading the British was General Charles Cornwallis. The French, who at this point had entered into an alliance to help the Americans, contributed troops that were led by the Comte de Rochambeau. Washington and Rochambeau led American and French troops from New York to Virginia in August 1781. De Grasse's French troops joined Lafayette's troops as well moving towards Virigina. ",
		winner: "Americans",
		loser: "British",
		people: "General George Washington, Comte de Rochambeau, General Charles Cornwallis, Marquis de Lafayette. ",
		killed_american: "88",
		wounded_american: "301",
		captured_american: "0",
		killed_british: "142-309",
		wounded_british: "326-595",
		captured_british: "7416-7685",
		consequences: "This was a definitive win for the Americans and with the capture and surrender of General Cornwallis signified the end of the war. The Treaty of Paris was signed on September 3, 1783 which formally ended the war.",
		left_coord: 0.62744140625,
		top_coord: 0.4588537839823659,
		img_url: "yorktown.jpg"
	},
	{
		event_name: "The Battle of Guilford Courthouse",
		date_start: moment([1781, 2, 15]),
		date_end: null,
		location: "Guilford Courthouse, North Carolina",
		description: "The British Army met the Continental Army in present day Greensboro, North Carolina. The British won this battle but sustained significant losses. Before the battle the British Army had controlled much of the southern territory including Georgia and South Carolina.",
		winner: "British",
		loser: "Americans",
		people: "General Nathanael Green and General Cornwallis",
		killed_american: "70",
		wounded_american: "185",
		captured_american: "1046",
		killed_british: "93",
		wounded_british: "413",
		captured_british: "26",
		consequences: "Though the British were outnumbered, they defeated the Americans. After this battle Cornwallis was captured and defeated at the Battle of Yorktown.",
		left_coord: 0.54638671875,
		top_coord: 0.5047759000734754,
		img_url: "guilford.jpg"
	}
];